all:
  hosts:
    AlienStoat
  children:
    apt_repositories:
      hosts:
        AlienStoat
    apt_packages:
      hosts:
        AlienStoat
    nodejs_gpg:
      hosts:
        AlienStoat
    asdf:
      hosts:
        AlienStoat
    keeagent:
      hosts:
        AlienStoat
