---
- name: apt packages
  apt:
    pkg:
    - socat
  become: yes

- name: deploy ~/bashrc.d/00-keeagent.sh
  template:
    src: ./~/.bashrc.d/00-keeagent.sh.j2
    dest: ~/.bashrc.d/00-keeagent.sh
    mode: '0640'
