---
- name: apt repositories
  hosts: apt_repositories
  roles:
    - { role: apt_repositories, become: yes, tags: ['apt_repositories'] }

- name: apt packages
  hosts: apt_packages
  roles:
    - { role: apt_packages, become: yes, tags: ['apt_packages'] }

- name: keeagent
  hosts: keeagent
  roles:
    - { role: keeagent, tags: ['keeagent'] }

- name: nodejs_gpg
  hosts: nodejs_gpg
  roles:
    - { role: nodejs_gpg, tags: ['nodejs_gpg'] }

- name: asdf
  hosts: asdf
  roles:
    - { role: markosamuli.asdf, tags: ['asdf'] }
